on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - docs/
      - "**/README.md"

  release:
    types: [published]

env:
  ECR_REPOSITORY: ht-sfmc

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push the image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IS_RELEASE: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        run: |
          IMAGE_TAG="edge"
          if [ "$IS_RELEASE" = "true" ]; then
            IMAGE_TAG="latest"
          fi

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
